version: "3.8"

services:
  frontend:
    build: .
    restart: unless-stopped
    ports:
      - "8001:5173"
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - app-network

#  caddy:
#    image: caddy:latest
#    restart: unless-stopped
#    depends_on:
#      - frontend
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile:ro
#      - caddy_data:/data
#      - caddy_config:/config
#    networks:
#      - app-network

volumes:
  frontend_node_modules:
#  caddy_data:
#  caddy_config:

networks:
  app-network:
    driver: bridge