name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem
          
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            set -e
            cd ~
            
            # Check if directory exists
            if [ ! -d "sandy-portfolio" ]; then
              git clone https://github.com/Santhakumar17/portfolio-demo.git sandy-portfolio
            fi
            
            cd sandy-portfolio
            git reset --hard
            git pull origin main
            
            sudo docker-compose down || true
            sudo docker-compose up --build -d
            
            sudo systemctl restart nginx
          EOF