name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            # Install docker-compose if not already
            if ! command -v docker-compose &> /dev/null
            then
              sudo apt-get update
              sudo apt-get install -y docker-compose
            fi
            
            # Clone or pull the repo
            if [ ! -d "sandy-portfolio" ]; then
              git clone https://github.com/Santhakumar17/portfolio-demo.git sandy-portfolio
            fi
            
            cd sandy-portfolio
            git pull origin main
            
            docker-compose down || true
            docker-compose up --build -d
            
            # Restart nginx with sudo
            sudo systemctl restart nginx
          EOF